dist: focal

language: c

sudo: required

os: linux

before_script:
    - sudo apt-get -y install lua5.1
    - sudo apt-get -y install luarocks
    - sudo luarocks install luaunit
    - sudo luarocks install mockagne

script:
     - sudo luarocks make
     - lua run_unit_tests.lua